version: '3.9'

services:

  backend:
    build: ./backend
    container_name: ttk-chess-backend
    ports:
      - "8484:8484"

  frontend:
    build: ./frontend
    container_name: ttk-chess-frontend
    ports:
      - "8483:3000"